lint:
  image: python:3.13
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

test:
  image: oven/bun:1
  stage: test
  script:
    - bun install
    - bun run build
    - bun run test

